create table if not exists brigades (
    uuid uuid not null,
    constraint brigades_pkey primary key (uuid)
    );
create table if not exists bags (
    id int not null generated by default as identity,
    weight int not null default 60,
    country varchar not null,
    percentage_of_robusta real not null,
    percentage_of_arabica real not null,
    variety varchar not null,
    brigade_uuid uuid,
    constraint bags_pkey primary key (id),
    constraint bags_brigade_uuid_fkey foreign key (brigade_uuid) references brigades (uuid) on delete cascade on update cascade
    );
create table if not exists roasting (
    id int not null generated by default as identity,
    brigade_uuid uuid not null,
    count_of_bags int not null,
    country varchar not null,
    variety varchar not null,
    output_weight int not null,
    constraint roasting_pkey primary key (id),
    constraint roasting_brigade_uuid_fkey foreign key (brigade_uuid) references brigades (uuid) on delete cascade on update cascade
    );